### ISSUE TITLE
Issues i noticed

### ISSUE THREAD

**Issue by SephVII** [suzaku01/mhf_questlists_reader#6]
I wanted to use the quest reader to translate the questlists file in an easier way then manually hex editing it.
but i noticed a few issues while doing so.

In the text Area only the "Title and name" changed if i try to change anything else it doesnt work i tried to save it multiple times and export it but nothing changes.
Also for whatever reason the first quest i saved the changes too got duplicated to the bottom of the Event Quest list in the LR/HR Quest Counter. But the only two button i hit and used where Save Changes and Export nothing else.

Hope it helps to imrpove the tool. ♥

**Comment by suzaku01** [comment]
> In the text Area only the "Title and name" changed if i try to change anything else it doesnt work i tried to save it multiple times and export it but nothing changes.

Don't forget to hit save button before you select other quest.
By the way, most quest data is stored in `mhfinf.bin`, but when questlist reads the data in the counter, it first checks if the ID of the quest is in `mhfinf.bin`, and if so, it takes the data from there and displays it. This means that if you want to change the data of an existing quest, you need to edit `mhfinf.bin`, not questlist.
If the ID is not in `mhfinf.bin` (e.g. musou, diva, custom quest), the data in the questlist is displayed as is.


> Also for whatever reason the first quest i saved the changes too got duplicated to the bottom of the Event Quest list in the LR/HR Quest Counter. But the only two button i hit and used where Save Changes and Export nothing else.

I didn't get this issue. 
Can you give me more details about this please?

**Comment by SephVII** [comment]
> > In the text Area only the "Title and name" changed if i try to change anything else it doesnt work i tried to save it multiple times and export it but nothing changes.
> 
> Don't forget to hit save button before you select other quest. By the way, most quest data is stored in `mhfinf.bin`, but when questlist reads the data in the counter, it first checks if the ID of the quest is in `mhfinf.bin`, and if so, it takes the data from there and displays it. This means that if you want to change the data of an existing quest, you need to edit `mhfinf.bin`, not questlist. If the ID is not in `mhfinf.bin` (e.g. musou, diva, custom quest), the data in the questlist is displayed as is.
> 
> > Also for whatever reason the first quest i saved the changes too got duplicated to the bottom of the Event Quest list in the LR/HR Quest Counter. But the only two button i hit and used where Save Changes and Export nothing else.
> 
> I didn't get this issue. Can you give me more details about this please?

Yeah i did hit Save after doing changes and then export everytime. i was working with the bin 0 for testing to translate the Event quests mostly.

I wish i could give you more details but all i did was using the Save button and then Export and pop there was an duplicate of the first Quest on the bottom idk why or how tho. Sorry  i wish i had more details it was the questbin_0 tho so the first event quest on the LR/HR counter.

**Comment by suzaku01** [comment]
I understand.
Anyway, thanks for the report.

**Comment by suzaku01** [comment]
I had that problem once yesterday, but I don't know why it happened.
Looking at the actual file, it didn't look like the problem was with the quest list itself.
Anyway, it still needs to be investigated.

**Comment by SephVII** [comment]
> 

Yeah i have no idea my question is if its a duplicate ? Added newly to the list or if it replaces the last quest in the list
