### ISSUE TITLE
Any plans for extending this ?

### ISSUE THREAD

**Issue by SephVII** [suzaku01/mhf_questlists_reader#7]
I noticed that you started a Quest Editor a while ago, when i look at this tool here it feels like an Quest editor already sort of not completly yet but now that this tools is getting more stable with you iron out some bugs.
Is there any plans to extend this one here to be a full quest editor at some point ? Like be able to edit even the quests in mhfinf file for example ?
Unless thats impossible for the reader no idea how this works code wise.

Regards Seph

**Comment by suzaku01** [comment]
For what purpose are you trying to edit mhfinf?

**Comment by SephVII** [comment]
Alright heres 2 things.

1. if we had a Quest Editor like quest list reader with actualy UI it would be way easier to handle Edits for the quests ingame... Low Rank , High Rank and G Rank etc... right now they are edited by changing it manually via hex edit but its a nightmare navigating through those files. Some sort of UI for it would be nice to streamline the process of manipulating Quests.

2. Monster stats, Monster stats are not stored in the quest files itself from what i know so not in "mhfinf". They are stored in the "mhfemd" even tho it could be also just the table in the "mhfemd". I wanted to edit those too and balance the monster stats out but i cant figure out no matter how long i spend in that file how to manipulate the stats and fix them as they are currently...

I remember in my old Project G for Monster Hunter Portable3rd we had a Quest Editor to change everything about any quest in the game all quest data and Monster stats etc... it was really handy and gave alot of freedom for customization etc so i though it would be cool to have for Frontier too....
But from what i understand this cant be done with the reader cause he only reads the data from mhdinf and doesnt really manipulate it right ?

**Comment by suzaku01** [comment]
>>1  I think that's a good idea, but it would take an enormous amount of time to implement it.

>> 2  I have heard that the list of monster strengths is stored in mhfemd.
Also, the strength of the monsters in the quests refer to the values in the quest file, so if you want to change that, you can edit the quest directly.

>> Reader does not read mhinf.
If I were to try to do the same thing with mhf as with 3rd, it would take an enormous amount of time.
I can't do it alone, and I'm sorry to say that I don't intend to do it at the moment.
