### ISSUE TITLE
Line breaks ?

### ISSUE THREAD

**Issue by SephVII** [suzaku01/mhf_questlists_reader#8]
I noticed that the game has line breaks for something like the "Clear condition" ingame. I cant figure out how to do line breaks in the quest reader tho or is there even a way to do so ?

**Comment by suzaku01** [comment]
Could you give me some more information?

**Comment by SephVII** [comment]
Here as you can see the quests have a line break each Condition is on a seperate line.

![grafik](https://user-images.githubusercontent.com/88888479/165506729-d28d6a04-87c1-4a25-a82c-8c7fd52c18c1.png)

Looking in the quest reader now i cant do any Line break myself the quest reader does already have some sort of a very Small "Space" inbetween both words which is the line break apparently but i cant copy and paste it.
And i tried somehow to insert a line break you would normall do but no success. If you accidently remove this premade linebreak space in the editor you can only align the conditions Horizontially afterwards.

**Comment by suzaku01** [comment]
Thank you for your infomation.
