### ISSUE TITLE
Item 1,2,3 rewards ?

### ISSUE THREAD

**Issue by SephVII** [suzaku01/mhf_questlists_reader#9]
Can we or wiill we be able to change the item / quest Rewards Item 1, 2 and 3 in the future ?

**Comment by suzaku01** [comment]
The actual reward items are referenced from the quest file.
Therefore, all questlist can do is change the display.

**Comment by SephVII** [comment]
> The actual reward items are referenced from the quest file. Therefore, all questlist can do is change the display.

I See unfourtanly
